### ISSUE TITLE
No picture when user not registered

### ISSUE THREAD

**Issue by goatandsheep** [lwhiteley/gravatar-api#1]
If user has not registered on gravatar you see the gravatar logo instead of the user's identicon. I recommend you add `?d=identicon` to the end of the image url to avoid this issue.

**Comment by lwhiteley** [comment]
You  can already do that by providing your own default. not sure what your request is about

```
var options = {
    email: 'test@gmail.com',
    parameters: { "size": "200", "d": "identicon" },
    secure: true
}
var avatar = gravatar.imageUrl(options);
// https://secure.gravatar.com/avatar/1aedb8d9dc4751e229a335e371db8058?size=200&d=identicon
```

Are you saying that the default should always be identicon?

if so, then that would be opinionated and not giving the api as is; left for the developer's interpretation.

as seen in the documentation:
![https://i.imgur.com/6dgiBtW.png](https://i.imgur.com/6dgiBtW.png)

**Comment by lwhiteley** [comment]
are you saying that there should always be a default?

**Comment by goatandsheep** [comment]
@lwhiteley I was saying that it should always be identicon, but you bring up a valid point that it is opinionated
