### ISSUE TITLE
Merge suggestion with emerleite/node-gravatar

### ISSUE THREAD

**Issue by goatandsheep** [lwhiteley/gravatar-api#2]
There is another npm project which also implements gravatar api. Is there a reason against merging this project with [emerleite/node-gravatar](https://github.com/emerleite/node-gravatar)? It is significantly more popular and appears to have the same functionality.

**Comment by lwhiteley** [comment]
will attempt probably. i made this to be compatible with react-native. where the lib you mentioned is not

**Comment by goatandsheep** [comment]
@lwhiteley if there is a list of specifications that you recommend would allow it to be compatible with react-native, let me know and might be able to help make those for you

**Comment by lwhiteley** [comment]
yea there's just one..

emerleite/node-gravatar is currently using the native node crypto library, where in react-native, native node libraries cannot be compiled.

To get around this i used [blueimp-md5](https://www.npmjs.com/package/blueimp-md5) to create the md5 hashes

So essentially, no packages native to node can be used when making a react-native compatible package

**Comment by goatandsheep** [comment]
https://github.com/emerleite/node-gravatar/issues/34

**Comment by lwhiteley** [comment]
would also need to add querystring as a dependency

**Comment by goatandsheep** [comment]
https://github.com/emerleite/node-gravatar/pull/35

**Comment by lwhiteley** [comment]
k ill deprecate this repo in favour of the other
